spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

  # S3 Bucket
  cloud:
    aws:
      region:
        static:
      credentials:
        accessKey:
        secretKey:
      s3:
        bucket:
        url:
